[package]
name = "git2-bug"
version = "0.1.0"
authors = ["Joel Nises <joel.nises@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
